### PR TITLE
Use cweid as plugin_id

### PR DESCRIPTION
**Pull request by aapomm**
### Spec
The `issueid` attribute that comes from the Veracode file is apparently not unique. This isn't an ideal use for the plugin_id since it will deduplicate distinct vulnerabilities.

**Proposed solution**
Use `cweid` as the plugin_id instead.

### CODE REVIEW

**Comment by tjarrettveracode** [comment]
FYI, `issueid` should be unique when combined with `app_id` and the scan type (static or dynamic). There may be many findings that have the same `cweid`.

**Comment by aapomm** [comment]
Hi @tjarrettveracode thanks for the heads up! I'm assuming the `app_id` changes with each scan? If so, we can't use `app_id` as the plugin identifier since we want the same findings to be deduplicated even though they're detected in different apps.

**Comment by tjarrettveracode** [comment]
Hi @aapomm , `app_id` will be consistent for scans of the same code base, but different between different apps. 

It is possible to have flaws that are the same between different code bases (e.g. there are shared libraries across applications), but the Veracode platform currently does not give those the same `issueid`.

**Comment by rachkor** [comment]
@tjarrettveracode I'm Rachael with the Dradis team and have a question for you. We're trying to understand what data does and doesn't change from one instance of a vulnerability to the next (both within and across scans). Since we're not Veracode users ourselves, we normally ask the Dradis users for this. 

Does data like the description change from one instance of a vuln to the next? Or is that information static? I know that info like the source file will change but I'm hoping you can clarify whether any of the information will be consistent across and within scans.

**Comment by tjarrettveracode** [comment]
Hi @rachkor - there is some information in the finding description that may change from one scan to the next depending on how the flaw was detected. We typically include a text summary of the attack surface (e.g. "parameter 1 in the function call to sql.execute comes from an HTTP query parameter which could be directly manipulated") in the description text, so that part might change along the way. 

Other information that will likely change is the exact line number on which the finding occurs -- we use some data about the structure of the application to match a finding from one scan to the next even if the code moves around. 

Happy to get on a call to discuss further with you if that would be useful.

**Comment by etdsoft** [comment]
@tjarrettveracode re:

> FYI, issueid should be unique when combined with app_id and the scan type (static or dynamic). There may be many findings that have the same cweid.

We need to cover two cases:

1. You upload the same scan twice, we don't want to end with 2x of everything.
2. You work on two different apps, that are vulnerable to the same issue, and you want to have your own custom recommendation on how to fix it.

Your proposal works great for 1 but doesn't work for 2. It would also seem to break for two partial scans agains the same app.

My understanding is that you have a database of checks you make, then depending on whether static or dynamic scan is performed, you do your magic and create a report with a bunch o issues identified by `issueid` that's unique in each scan. You don't include the internal check ID in the scan output.

From your comments:

> There may be many findings that have the same cweid.

and 

> It is possible to have flaws that are the same between different code bases (e.g. there are shared libraries across applications), but the Veracode platform currently does not give those the same issueid.


I'm thinking that the combination of "CWE ID" + "issue title" (or a hash of the title), could be a good proxy for check ID that can be used to de-dup in scans of different apps. Would that work?

**Pull request closed without merging**
